# metadata
run_name: 'map_wide'
logging: 'True'

# characteristic number for map
perf_num: 6

# map paths
map_path: './Spielberg_map'
map_ext: '.png'

# starting pose for map
sx: -0.044081
sy: -0.849163
stheta: 3.4034118

# raceline path and indices
wpt_path: './Spielberg_raceline.csv'
wpt_path2: './Spielberg_centerline.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5

# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.0
vgain_min: 0.5
vgain_max: 1.5

# computation budget
popsize: 100
budget: 1000

# optimisation method
optim_method: 'CMA'

# seed
seed: 12345

# PPO parameters
ppo_params:
  gamma: 0.99
  alpha: 0.0003  # Learning rate for actor and critic
  gae_lambda: 0.95
  policy_clip: 0.2 
  batch_size: 64
  n_epochs: 4
  learning_rate: 0.0003
  max_steps_per_episode: 5000      # maximum steps that can be reached eventually
  initial_max_steps: 1000          # starting max steps for curriculum
  final_max_steps: 5000            # final max steps after curriculum_episodes
  curriculum_episodes: 500         # over how many episodes to gradually increase
  update_interval: 128             # Match with batch_size
  clip_range: 0.2
  value_loss_coef: 0.5
  entropy_coef: 0.01
