# metadata
run_name: 'ddpg_map_wide'
logging: 'True'

# characteristic number for map
perf_num: 6

# map paths
map_path: './Spielberg_map'
map_ext: '.png'

# starting pose for map
sx: -0.044081
sy: -0.849163
stheta: 3.4034118

sx2: -72.7851387
sy2: 47.1581236
stheta2: 2.3546648

sx3: 2.6599770
sy3: -0.1246830
stheta3: 3.4

# raceline path and indices
wpt_path: './Spielberg_raceline.csv'
wpt_path2: './Spielberg_centerline.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5

# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
tlad_min: 0.2
tlad_max: 5.0
vgain_min: 0.5
vgain_max: 1.5

# computation budget
popsize: 100
budget: 1000

# DDPG-specific parameters
ddpg_params:
  actor_lr: 0.0001       # Learning rate for actor
  critic_lr: 0.001       # Learning rate for critic
  gamma: 0.99            # Discount factor
  tau: 0.005             # Soft update rate for target networks
  replay_buffer_size: 1000000 # Maximum size of the replay buffer
  batch_size: 64         # Mini-batch size for training
  fc1_dims: 400          # Number of units in the first layer
  fc2_dims: 300          # Number of units in the second layer
  max_steps_per_episode: 1000 # Maximum steps per episode
  exploration_noise: 0.1 # Exploration noise standard deviation

# seed
seed: 12345
